#+LATEX_HEADER: \usepackage{ctex}
#+TITLE: C++ Primer 阅读指导
#+AUTHOR: 林懿伦
#+DATE: 2015 年 8 月 31 日

* Week 1 : C++基础入门

** 第1章 : 开始

*** 章节导读
    本章通过一个示例程序入手，开始接触C++数据类型，变量，表达式及函数等基本概念。这一章仅对于完全没有编程基础的同学而言有一定难度，需要把每个代码示例完成并编译运行，查看输入与输出来理解程序的含义。

    本章阅读过程中请完成下述任务：
    1. 按照章节的介绍完成书中的示例程序，并充分理解程序的每一部分。
    2. 程序完成后，使用g++进行编译并运行，同时查看运行的输出结果。

*** 课后练习
    书中练习较多，本章建议完成练习1.3，1.11，1.15，1.23，1.25。

**** 练习1.3
#+BEGIN_SRC C++
#include <iostream>
/*
 ,*Author: Гагарин
 ,*Date: 2015-08-31
 ,*/
int main()
{
    std::cout << "Oh great user! Whats' your name, may I ask ?" << std::endl
              << "I'm: ";
    std::string user = "";
    std::cin >> user;
    std::cout << "Hello, " << user << "!" << std::endl;
    return 0;
}
#+END_SRC

**** 嵌套注释
     #+BEGIN_SRC C++ :results raw :exports both
     #include <iostream>

     int main()
     {
     std:cout << ""
     }
     #+END_SRC
**** 练习1.11
     #+BEGIN_SRC C++

     #+END_SRC
*** 核心知识点
- 如何编译及运行一个简单的C++程序
- 基本的输入与输出（ =stdin= 与  =stdout= ）及 =iostream= 库如何使用
- C++的控制流（ =if= ， =for= ， =while= ）
- C++的类与成员函数的基本概念，简单理解即可，后面章节会详细介绍
- 简单的书店程序编写、编译与测试

** 第2章 : 变量和基本类型

*** 章节导读

 本章介绍C++中的数据类型，以及如何存储和操作数据。请按照书籍要求完成基本类型的学习并开始学习C++标准库里的复杂类型。

 本章练习都非常基础，有助于对数据类型的理解，建议全部完成。

*** 核心知识点

 核心知识点包含：

 - C++的内置类型的概念及使用场景：bool char short int long float double
 - *【难点】* [fn:1]不同数据类型间类型转换的方法及预期结果
 - 作用域的概念
 - 如何定义和使用变量
 - *【难点】*  复合类型的概念与使用（引用，指针）
 - const 限定符的使用，const 的引用以及指针部分比较难理解
 - 使用 typedef 定义数据类型的别名
 - auto 的使用场景，delcltype 使用不多简单了解即可
 - 如何自定义更复杂的数据结构，使用 struct
 - 头文件编写以及头文件保护符的使用


** 第3章 : 字符串、向量和数组

*** 章节导读

 本章是对第二章节的延伸，介绍更复杂的数据类型string，vector，迭代器及数组，以及它们之间的关系。

 建议完成本章的练习：3.4，3.10，3.14，3.20，3.23，3.36，3.40

*** 核心知识点

 本章的核心知识点包含：

 - using 命名空间使用方式
 - 使用标准库类型 string 定义及处理字符串：初始化 string 对象，对字符串进行各种操作，访问对象中的每个字符
 - 使用标准库类型 vector 定义及处理向量：初始化 vector 对象，对 vector 进行添加删除元素等操作
 - *【难点】* 使用迭代器来循环访问向量/字符串中的元素：迭代器的使用方法，迭代器运算，begin 与 end运算符
 - C++数组的定义、初始化及与指针的关系：数组的定义及初始化，访问和操作数组元素
 - *【难点】* 了解多维数组，指针及数组地址的理解，多维数组的访问方法
* Footnotes

[fn:1] 标注【难点】的内容需要花费更多时间仔细阅读理解。
